#!/usr/bin/env python
import cPickle as pickle
import sys

from morfessor import diagnostics
from morfessor.exception import ArgumentException

if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise ArgumentException('Expects filename of picked stats object as argument')
    with open(sys.argv[1], 'r') as fobj:
        stats = pickle.load(fobj)
        isp = diagnostics.IterationStatisticsPlotter(stats)
        isp.all()

