#!/usr/bin/env python

import sys

from flatcat import cmd
from flatcat.exception import ArgumentException
from flatcat.flatcat import _logger


def main(argv):
    parser = cmd.get_reformat_argparser()
    try:
        args = parser.parse_args(argv)
        cmd.reformat_main(args)
    except ArgumentException as e:
        parser.error(e)
    except Exception as e:
        _logger.error("Fatal Error %s %s" % (type(e), e))
        raise


if __name__ == "__main__":
    main(sys.argv[1:])
