#!/usr/bin/env python

import sys

import flatcat
from flatcat import cmd
from flatcat.flatcat import _logger

def main(argv):
    parser = cmd.get_evaluation_argparser()
    try:
        args = parser.parse_args(argv)
        cmd.main_evaluation(args)
    except flatcat.ArgumentException as e:
        parser.error(e)
    except Exception as e:
        _logger.error("Fatal Error %s %s" % (type(e), e))
        raise

if __name__ == "__main__":
    main(sys.argv[1:])
