#!/usr/bin/env python

import sys

from morfessor import catmap


def main(argv):
    parser = catmap.get_default_argparser()
    try:
        args = parser.parse_args(argv)
        catmap.main(args)
    except catmap.ArgumentException as e:
        parser.error(e)
    except Exception as e:
        catmap._logger.error("Fatal Error %s %s" % (type(e), e))
        raise


if __name__ == "__main__":
    main(sys.argv[1:])
